# -*- coding: utf-8 -*-
"""Sales_Analysis_Portfolio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P-WMnZY2UG8JnGSuv5sVrVX8dd1jXBjb
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import streamlit as st
import random
from faker import Faker

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import streamlit as st

#now we import the dataset here
df=pd.read_csv('/content/sales_analysis_portfolio_dataset.csv')
#now read first five rows
df.head()

#now we clean the data
df.info()

#now analysis of total sales,quantity,average unit price of each category,sales by branch,average sales by category,category sale gender wise
total_sales=df['Total'].sum()
print(total_sales)
Quantity=df['Quantity'].sum()
print(Quantity)
Average_unit_price=df['Unit Price'].mean()
print(Average_unit_price)
sales_by_branch=df.groupby('Branch')['Total'].sum()
print(sales_by_branch)
average_sales_by_category=df.groupby('Product Category')['Total'].mean()
print(average_sales_by_category)
category_sale_gender_wise=df.groupby(['Product Category','Gender'])['Total'].sum()
print(category_sale_gender_wise)

import seaborn as sns
import matplotlib.pyplot as plt

# Sales by branch
palette = sns.color_palette("Set2", n_colors=len(sales_by_branch))
sns.barplot(x=sales_by_branch.index, y=sales_by_branch.values, palette=palette)
plt.title("Sales by Branch")
plt.xlabel("Branch")
plt.ylabel("Total Sales")
plt.show()
# Top 10 products
top_products = df.groupby('Product')['Quantity'].sum().nlargest(10)
sns.barplot(x=top_products.values, y=top_products.index)
plt.title("Top 10 Products by Quantity Sold")
plt.xlabel("Quantity")
plt.ylabel("Product")
plt.show()
# Plot with custom colors
sns.countplot(data=df, x='Payment', palette=colors)
plt.title("Payment Method Distribution")
plt.xlabel("Payment Method")
plt.ylabel("Count")
plt.show()
#average sales category wise
sns.barplot(x=average_sales_by_category.index, y=average_sales_by_category.values)
plt.title("Average Sales by Category")
plt.xlabel("Category")
plt.ylabel("Average Sales")
plt.show()

# streamlit_app.py
import streamlit as st

st.title("📊 Sales Analysis Dashboard")

st.write("### Key Metrics")
st.metric("Total Sales", f"${df['Total'].sum():,.2f}")
st.metric("Total Quantity Sold", int(df['Quantity'].sum()))
st.metric("Average Rating", round(df['Rating'].mean(), 2))

# Branch-wise sales
st.write("### Sales by Branch")
branch_sales = df.groupby('Branch')['Total'].sum()
st.bar_chart(branch_sales)

# Top Products
st.write("### Top 10 Products by Quantity")
top_products = df.groupby('Product')['Quantity'].sum().nlargest(10)
st.bar_chart(top_products)

# Monthly sales line chart
df['Month'] = df['Date'].dt.to_period('M').astype(str)
monthly_sales = df.groupby('Month')['Total'].sum()
st.line_chart(monthly_sales)

# Filter by branch and view raw data
branch_filter = st.selectbox("Select Branch", df['Branch'].unique())
st.write(df[df['Branch'] == branch_filter])